version = 0.1

[default.global.parameters]
stack_name = "finance4tura-backend"

[default.build.parameters]
cached = true
parallel = true

[default.local_start_api.parameters]
warm_containers = "EAGER"
parameter_overrides = "DynamoDbEndpoint=http://host.docker.internal:8000"

[default.deploy.parameters]
region = "eu-central-1"
capabilities = "CAPABILITY_IAM"
resolve_s3 = true
confirm_changeset = false
parameter_overrides = "GoogleClientId=887159107424-2g02147g1s2lvhanbjnl1i3u68okskr1.apps.googleusercontent.com"
