const s = {
  root: {
    display:       "flex",
    flexDirection: "column",
    flex:          1,
    minHeight:     0,
    overflow:      "hidden",
    margin:        "-28px -32px 0",
  },
  center: {
    display:        "flex",
    alignItems:     "center",
    justifyContent: "center",
    flex:           1,
    color:          "var(--text-muted)",
    fontSize:       "14px",
  },
  tabBar: {
    display:      "flex",
    gap:          "4px",
    padding:      "10px 24px 8px",
    background:   "var(--surface)",
    borderBottom: "1px solid var(--border)",
    flexShrink:   0,
    flexWrap:     "wrap",
  },
  tabBtn: {
    background:     "var(--surface-2)",
    border:         "none",
    outline:        "none",
    boxShadow:      "none",
    textDecoration: "none",
    borderRadius:   "8px",
    padding:        "6px 16px",
    fontSize:       "13px",
    fontWeight:     500,
    color:          "var(--text)",
    cursor:         "pointer",
    fontFamily:     "inherit",
    letterSpacing:  "0.01em",
    transition:     "background 0.15s, color 0.15s",
  },
  tabBtnActive: {
    background: "var(--accent)",
    color:      "#fff",
    fontWeight: 700,
  },
  content: {
    flex:      1,
    minHeight: 0,
    overflowY: "auto",
  },
  tabContent: {
    padding:       "14px 24px",
    display:       "flex",
    flexDirection: "column",
    gap:           "16px",
  },
  toolbar: {
    display:        "flex",
    alignItems:     "center",
    justifyContent: "space-between",
    flexWrap:       "wrap",
    gap:            "8px",
  },
  toolbarTitle: {
    fontSize:   "15px",
    fontWeight: 700,
    color:      "var(--text)",
    display:    "flex",
    alignItems: "center",
    gap:        "6px",
  },
  count: {
    background:   "var(--surface-2)",
    border:       "1px solid var(--border)",
    borderRadius: "10px",
    padding:      "1px 7px",
    fontSize:     "11px",
    fontWeight:   500,
    color:        "var(--text-muted)",
  },
  empty: {
    color:     "var(--text-muted)",
    fontSize:  "13px",
    fontStyle: "italic",
    padding:   "24px 0",
    textAlign: "center",
  },
  // Section within a location tab
  section: {
    display:       "flex",
    flexDirection: "column",
    gap:           "8px",
  },
  sectionHeader: {
    display:        "flex",
    alignItems:     "center",
    justifyContent: "space-between",
    gap:            "8px",
    padding:        "6px 0",
    borderBottom:   "1px solid var(--border)",
  },
  sectionTitle: {
    fontSize:   "14px",
    fontWeight: 700,
    color:      "var(--text)",
  },
  // Cards grid
  cardGrid: {
    display:             "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(280px, 1fr))",
    gap:                 "14px",
  },
  card: {
    background:    "var(--surface)",
    border:        "1px solid var(--border)",
    borderRadius:  "12px",
    padding:       "14px 16px",
    display:       "flex",
    flexDirection: "column",
    gap:           "10px",
  },
  cardTop: {
    display:        "flex",
    justifyContent: "space-between",
    alignItems:     "flex-start",
    gap:            "8px",
  },
  cardName: {
    fontSize:   "14px",
    fontWeight: 700,
    color:      "var(--text)",
  },
  cardSub: {
    fontSize:  "11px",
    color:     "var(--text-muted)",
    marginTop: "2px",
  },
  cardActions: {
    display:    "flex",
    gap:        "4px",
    flexShrink: 0,
  },
  metaRow: {
    display:  "flex",
    gap:      "6px",
    flexWrap: "wrap",
  },
  metaBadge: {
    background:   "var(--surface-2)",
    border:       "1px solid var(--border)",
    borderRadius: "8px",
    padding:      "2px 8px",
    fontSize:     "11px",
    color:        "var(--text-muted)",
  },
  // Table
  tableWrap: {
    overflowX:    "auto",
    borderRadius: "10px",
    border:       "1px solid var(--border)",
  },
  table: {
    width:          "100%",
    borderCollapse: "collapse",
    fontSize:       "12px",
  },
  th: {
    padding:      "5px 7px",
    textAlign:    "left",
    fontWeight:   600,
    color:        "var(--text-muted)",
    background:   "var(--surface)",
    borderBottom: "1px solid var(--border)",
    whiteSpace:   "nowrap",
    fontSize:     "11px",
  },
  thRight: {
    padding:      "5px 7px",
    textAlign:    "right",
    fontWeight:   600,
    color:        "var(--text-muted)",
    background:   "var(--surface)",
    borderBottom: "1px solid var(--border)",
    whiteSpace:   "nowrap",
    fontSize:     "11px",
  },
  tr: {
    borderBottom: "1px solid var(--border)",
  },
  td: {
    padding:   "5px 7px",
    color:     "var(--text)",
    whiteSpace: "nowrap",
  },
  tdRight: {
    padding:   "5px 7px",
    color:     "var(--text)",
    whiteSpace: "nowrap",
    textAlign: "right",
  },
  tdTrunc: {
    padding:      "5px 7px",
    color:        "var(--text)",
    maxWidth:     "160px",
    overflow:     "hidden",
    textOverflow: "ellipsis",
    whiteSpace:   "nowrap",
  },
  inlineEditRow: {
    background:   "rgba(134,239,172,0.06)",
    borderBottom: "1px solid var(--border)",
    borderLeft:   "3px solid var(--badge-text)",
  },
  inlineInput: {
    background:   "var(--surface)",
    border:       "1px solid var(--border)",
    borderRadius: "5px",
    color:        "var(--text)",
    fontSize:     "12px",
    padding:      "4px 6px",
    outline:      "none",
    fontFamily:   "inherit",
    boxSizing:    "border-box",
    transition:   "border-color 0.15s",
  },
  // Modal
  overlay: {
    position:       "fixed",
    inset:          0,
    background:     "rgba(0,0,0,0.55)",
    zIndex:         500,
    display:        "flex",
    alignItems:     "center",
    justifyContent: "center",
    padding:        "16px",
  },
  modal: {
    background:    "var(--surface)",
    border:        "1px solid var(--border)",
    borderRadius:  "14px",
    width:         "100%",
    maxWidth:      "520px",
    maxHeight:     "90vh",
    display:       "flex",
    flexDirection: "column",
    boxShadow:     "0 30px 60px rgba(0,0,0,0.4)",
  },
  modalHeader: {
    display:        "flex",
    alignItems:     "center",
    justifyContent: "space-between",
    padding:        "14px 18px",
    borderBottom:   "1px solid var(--border)",
    flexShrink:     0,
  },
  modalTitle: {
    fontSize:   "14px",
    fontWeight: 700,
    color:      "var(--text)",
  },
  modalClose: {
    background: "transparent",
    border:     "none",
    color:      "var(--text-muted)",
    fontSize:   "16px",
    cursor:     "pointer",
    lineHeight: 1,
    padding:    "2px 4px",
  },
  modalBody: {
    padding:       "18px",
    overflowY:     "auto",
    flex:          1,
    display:       "flex",
    flexDirection: "column",
    gap:           "12px",
  },
  modalFooter: {
    display:        "flex",
    justifyContent: "flex-end",
    gap:            "8px",
    paddingTop:     "8px",
    marginTop:      "4px",
    borderTop:      "1px solid var(--border)",
  },
  formError: {
    background:   "var(--error-bg, rgba(239,68,68,0.1))",
    border:       "1px solid var(--danger)",
    borderRadius: "7px",
    color:        "var(--danger)",
    fontSize:     "12px",
    padding:      "7px 12px",
  },
  fieldGroup: {
    display:       "flex",
    flexDirection: "column",
    gap:           "5px",
  },
  label: {
    fontSize:      "11px",
    fontWeight:    600,
    color:         "var(--text-muted)",
    textTransform: "uppercase",
    letterSpacing: "0.04em",
  },
  input: {
    background:  "var(--surface-2)",
    border:      "1px solid var(--border)",
    borderRadius:"7px",
    color:       "var(--text)",
    fontSize:    "13px",
    padding:     "7px 10px",
    outline:     "none",
    width:       "100%",
    boxSizing:   "border-box",
    fontFamily:  "inherit",
    transition:  "border-color 0.15s",
  },
  select: {
    background:   "var(--surface-2)",
    border:       "1px solid var(--border)",
    borderRadius: "7px",
    color:        "var(--text)",
    fontSize:     "13px",
    padding:      "7px 10px",
    outline:      "none",
    width:        "100%",
    boxSizing:    "border-box",
    fontFamily:   "inherit",
    cursor:       "pointer",
  },
  // Buttons
  btnPrimary: {
    background:   "var(--accent)",
    color:        "#000",
    border:       "none",
    borderRadius: "8px",
    padding:      "7px 16px",
    fontSize:     "13px",
    fontWeight:   600,
    cursor:       "pointer",
    fontFamily:   "inherit",
    transition:   "opacity 0.15s",
  },
  btnSecondary: {
    background:   "transparent",
    border:       "1px solid var(--border)",
    borderRadius: "8px",
    color:        "var(--text-muted)",
    padding:      "7px 16px",
    fontSize:     "13px",
    fontWeight:   500,
    cursor:       "pointer",
    fontFamily:   "inherit",
  },
  btnSm: {
    background:   "transparent",
    border:       "1px solid var(--border)",
    borderRadius: "6px",
    color:        "var(--text-muted)",
    padding:      "4px 10px",
    fontSize:     "11px",
    cursor:       "pointer",
    fontFamily:   "inherit",
    flexShrink:   0,
  },
  btnIcon: {
    background:   "transparent",
    border:       "none",
    color:        "var(--text-muted)",
    fontSize:     "14px",
    cursor:       "pointer",
    padding:      "3px 5px",
    borderRadius: "5px",
    lineHeight:   1,
    transition:   "color 0.15s",
  },
  btnIconSm: {
    background:   "transparent",
    border:       "none",
    color:        "var(--text-muted)",
    fontSize:     "12px",
    cursor:       "pointer",
    padding:      "2px 4px",
    borderRadius: "4px",
    lineHeight:   1,
  },
  // Settings section
  settingsSection: {
    display:       "flex",
    flexDirection: "column",
    gap:           "10px",
  },
  settingsSectionTitle: {
    fontSize:      "12px",
    fontWeight:    700,
    color:         "var(--text-muted)",
    textTransform: "uppercase",
    letterSpacing: "0.06em",
    marginBottom:  "4px",
  },
  locationRow: {
    display:        "flex",
    alignItems:     "center",
    justifyContent: "space-between",
    padding:        "10px 14px",
    background:     "var(--surface)",
    border:         "1px solid var(--border)",
    borderRadius:   "9px",
  },
  locationRowName: {
    fontSize:   "13px",
    fontWeight: 600,
    color:      "var(--text)",
  },
  locationRowAddr: {
    fontSize:  "11px",
    color:     "var(--text-muted)",
    marginTop: "2px",
  },
  thComputed: {
    padding:      "5px 7px",
    textAlign:    "right",
    fontWeight:   600,
    color:        "var(--text-muted)",
    background:   "rgba(56,189,248,0.08)",
    borderBottom: "1px solid var(--border)",
    borderLeft:   "2px solid rgba(56,189,248,0.25)",
    whiteSpace:   "nowrap",
    fontSize:     "11px",
  },
  tdComputed: {
    padding:    "5px 7px",
    textAlign:  "right",
    whiteSpace: "nowrap",
    color:      "var(--text)",
    background: "rgba(56,189,248,0.08)",
    borderLeft: "2px solid rgba(56,189,248,0.25)",
    fontWeight: 600,
  },
  // Dashboard cards
  dashGrid: {
    display:             "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(300px, 1fr))",
    gap:                 "16px",
  },
  dashCard: {
    background:    "var(--surface)",
    border:        "1px solid var(--border)",
    borderRadius:  "12px",
    padding:       "16px",
    display:       "flex",
    flexDirection: "column",
    gap:           "10px",
  },
  dashCardTitle: {
    fontSize:    "15px",
    fontWeight:  700,
    color:       "var(--text)",
    paddingBottom:"8px",
    borderBottom:"1px solid var(--border)",
  },
  dashTemplateRow: {
    display:       "flex",
    flexDirection: "column",
    gap:           "4px",
    padding:       "8px 0",
    borderBottom:  "1px solid var(--border)",
  },
  dashTemplateName: {
    fontSize:   "12px",
    fontWeight: 600,
    color:      "var(--text)",
  },
  dashTemplateDate: {
    fontSize: "11px",
    color:    "var(--text-muted)",
  },
  dashParamRow: {
    display:  "flex",
    gap:      "8px",
    flexWrap: "wrap",
    marginTop:"4px",
  },
  dashParamChip: {
    background:   "var(--surface-2)",
    border:       "1px solid var(--border)",
    borderRadius: "6px",
    padding:      "2px 8px",
    fontSize:     "11px",
    color:        "var(--text-muted)",
  },
};

export default s;
